export interface RegionMapConfig {
  nameEs: string;
  image: string;
  /**
   * Si es true, el mapa solo se muestra como imagen de referencia y no se
   * intentan cargar pines ni encuentros desde la PokéAPI. Se usa para zonas
   * sin datos (DLC) y para mapas reales aún sin pines recalibrados.
   */
  imageOnly?: boolean;
  /**
   * Proporción CSS (aspect-ratio) de la imagen, p.ej. '736 / 649'. Por
   * defecto los mapas estilizados son cuadrados ('1 / 1').
   */
  aspect?: string;
}

export const REGION_CONFIGS: Record<string, RegionMapConfig> = {
  // Mapas reales de WikiDex con pines recalibrados a la imagen.
  kanto:    { nameEs: 'Kanto',    image: '/maps/kanto.png',  aspect: '736 / 649'  },
  johto:    { nameEs: 'Johto',    image: '/maps/johto.png',  aspect: '215 / 149'  },
  hoenn:    { nameEs: 'Hoenn',    image: '/maps/hoenn.png',  aspect: '320 / 210'  },
  // Mapas reales de WikiDex (pines pendientes de recalibrar → imageOnly).
  sinnoh:   { nameEs: 'Sinnoh',   image: '/maps/sinnoh.png', imageOnly: true, aspect: '1268 / 734' },
  unova:    { nameEs: 'Unova',    image: '/maps/unova.png',  imageOnly: true, aspect: '256 / 168'  },
  kalos:    { nameEs: 'Kalos',    image: '/maps/kalos.png',  imageOnly: true, aspect: '320 / 210'  },
  galar:    { nameEs: 'Galar',    image: '/maps/galar.png',  imageOnly: true, aspect: '3460 / 6992' },
  hisui:    { nameEs: 'Hisui',    image: '/maps/hisui.png',  imageOnly: true, aspect: '1280 / 720' },
  paldea:   { nameEs: 'Paldea',   image: '/maps/paldea.png', imageOnly: true, aspect: '1 / 1'      },
  // Mapas estilizados cuadrados con pines + encuentros.
  alola:    { nameEs: 'Alola',    image: '/maps/alola.svg'    },
  // Expansiones de Galar (Espada/Escudo) — solo referencia.
  'isle-of-armor': { nameEs: 'Isla de la Armadura',  image: '/maps/isle-of-armor.png', imageOnly: true, aspect: '1282 / 1282' },
  'crown-tundra':  { nameEs: 'Nieves de la Corona',  image: '/maps/crown-tundra.png',  imageOnly: true, aspect: '1984 / 2060' },
  // Expansiones de Paldea (Escarlata/Púrpura) — solo referencia.
  kitakami: { nameEs: 'Noroteo',  image: '/maps/kitakami.png', imageOnly: true, aspect: '1 / 1' },
  biodomo:  { nameEs: 'Biodomo',  image: '/maps/biodomo.png',  imageOnly: true, aspect: '1 / 1' },
};

// Percentage coordinates (x, y) mapped to each region's PNG image.
// Key: PokéAPI parent location slug (location.name, not location-area.name).
export const LOCATION_COORDS: Record<string, { x: number; y: number }> = {

  // ── KANTO (calibrado al mapa LGPE de WikiDex, 736×649) ──────────────────────
  'pallet-town':           { x: 18, y: 70 },
  'viridian-city':         { x: 18, y: 55 },
  'pewter-city':           { x: 15, y: 19 },
  'cerulean-city':         { x: 58, y: 13 },
  'vermilion-city':        { x: 62, y: 52 },
  'lavender-town':         { x: 83, y: 30 },
  'celadon-city':          { x: 44, y: 30 },
  'fuchsia-city':          { x: 49, y: 78 },
  'saffron-city':          { x: 60, y: 30 },
  'cinnabar-island':       { x: 18, y: 92 },
  'indigo-plateau':        { x: 7,  y: 10 },
  'route-1':               { x: 18, y: 63 },
  'route-2':               { x: 16, y: 38 },
  'route-3':               { x: 26, y: 14 },
  'route-4':               { x: 46, y: 14 },
  'route-5':               { x: 58, y: 21 },
  'route-6':               { x: 61, y: 42 },
  'route-7':               { x: 52, y: 29 },
  'route-8':               { x: 72, y: 30 },
  'route-9':               { x: 70, y: 13 },
  'route-10':              { x: 80, y: 20 },
  'route-11':              { x: 72, y: 52 },
  'route-12':              { x: 83, y: 44 },
  'route-13':              { x: 76, y: 60 },
  'route-14':              { x: 67, y: 66 },
  'route-15':              { x: 58, y: 73 },
  'route-16':              { x: 35, y: 38 },
  'route-17':              { x: 28, y: 55 },
  'route-18':              { x: 40, y: 74 },
  'route-19':              { x: 49, y: 86 },
  'route-20':              { x: 37, y: 89 },
  'route-21':              { x: 18, y: 82 },
  'route-22':              { x: 10, y: 52 },
  'route-23':              { x: 6,  y: 22 },
  'route-24':              { x: 58, y: 7  },
  'route-25':              { x: 69, y: 7  },
  'viridian-forest':       { x: 14, y: 33 },
  'mt-moon':               { x: 34, y: 15 },
  'rock-tunnel':           { x: 80, y: 15 },
  'power-plant':           { x: 86, y: 22 },
  'safari-zone-kanto':     { x: 50, y: 71 },
  'seafoam-islands':       { x: 30, y: 90 },
  'pokemon-mansion':       { x: 16, y: 93 },
  'victory-road-kanto':    { x: 6,  y: 16 },
  'cerulean-cave':         { x: 53, y: 10 },
  'digletts-cave':         { x: 70, y: 48 },
  'pokemon-tower':         { x: 85, y: 28 },
  'silph-co':              { x: 61, y: 31 },

  // ── JOHTO (calibrado al mapa GSC de WikiDex, 215×149 — aproximado) ──────────
  'new-bark-town':         { x: 82, y: 73 },
  'cherrygrove-city':      { x: 62, y: 73 },
  'violet-city':           { x: 54, y: 32 },
  'azalea-town':           { x: 38, y: 71 },
  'goldenrod-city':        { x: 40, y: 61 },
  'ecruteak-city':         { x: 38, y: 31 },
  'olivine-city':          { x: 16, y: 58 },
  'cianwood-city':         { x: 9,  y: 66 },
  'mahogany-town':         { x: 76, y: 31 },
  'blackthorn-city':       { x: 82, y: 28 },
  'mt-silver':             { x: 88, y: 47 },
  'route-29':              { x: 72, y: 73 },
  'route-30':              { x: 60, y: 62 },
  'route-31':              { x: 60, y: 38 },
  'route-32':              { x: 52, y: 44 },
  'route-33':              { x: 45, y: 62 },
  'route-34':              { x: 40, y: 68 },
  'route-35':              { x: 40, y: 50 },
  'route-36':              { x: 47, y: 40 },
  'route-37':              { x: 44, y: 36 },
  'route-38':              { x: 28, y: 44 },
  'route-39':              { x: 22, y: 50 },
  'route-40':              { x: 14, y: 68 },
  'route-41':              { x: 16, y: 75 },
  'route-42':              { x: 62, y: 30 },
  'route-43':              { x: 70, y: 24 },
  'route-44':              { x: 80, y: 38 },
  'route-45':              { x: 85, y: 40 },
  'route-46':              { x: 78, y: 46 },
  'sprout-tower':          { x: 54, y: 27 },
  'ruins-of-alph':         { x: 50, y: 40 },
  'union-cave':            { x: 48, y: 50 },
  'slowpoke-well':         { x: 38, y: 74 },
  'ilex-forest':           { x: 42, y: 72 },
  'national-park':         { x: 44, y: 44 },
  'burned-tower':          { x: 40, y: 28 },
  'tin-tower':             { x: 35, y: 28 },
  'mt-mortar':             { x: 64, y: 30 },
  'lake-of-rage':          { x: 62, y: 15 },
  'dark-cave':             { x: 66, y: 38 },
  'ice-path':              { x: 84, y: 32 },
  'dragons-den':           { x: 86, y: 24 },
  'whirl-islands':         { x: 28, y: 64 },
  'mt-silver-cave':        { x: 88, y: 47 },

  // ── HOENN (calibrado al mapa RSE de WikiDex, 320×210 — aproximado) ──────────
  'littleroot-town':       { x: 43, y: 93 },
  'oldale-town':           { x: 40, y: 85 },
  'petalburg-city':        { x: 9,  y: 64 },
  'rustboro-city':         { x: 4,  y: 37 },
  'dewford-town':          { x: 16, y: 94 },
  'slateport-city':        { x: 33, y: 73 },
  'mauville-city':         { x: 34, y: 42 },
  'verdanturf-town':       { x: 29, y: 48 },
  'fallarbor-town':        { x: 18, y: 12 },
  'lavaridge-town':        { x: 33, y: 32 },
  'fortree-city':          { x: 53, y: 28 },
  'lilycove-city':         { x: 65, y: 27 },
  'mossdeep-city':         { x: 93, y: 52 },
  'sootopolis-city':       { x: 75, y: 52 },
  'ever-grande-city':      { x: 93, y: 65 },
  'pacifidlog-town':       { x: 62, y: 68 },
  'route-101':             { x: 42, y: 89 },
  'route-102':             { x: 25, y: 73 },
  'route-103':             { x: 45, y: 78 },
  'route-104':             { x: 7,  y: 52 },
  'route-105':             { x: 3,  y: 62 },
  'route-106':             { x: 10, y: 82 },
  'route-107':             { x: 22, y: 90 },
  'route-108':             { x: 28, y: 86 },
  'route-109':             { x: 33, y: 82 },
  'route-110':             { x: 33, y: 58 },
  'route-111':             { x: 34, y: 25 },
  'route-112':             { x: 30, y: 30 },
  'route-113':             { x: 26, y: 13 },
  'route-114':             { x: 11, y: 20 },
  'route-115':             { x: 5,  y: 25 },
  'route-116':             { x: 16, y: 37 },
  'route-117':             { x: 30, y: 46 },
  'route-118':             { x: 45, y: 42 },
  'route-119':             { x: 50, y: 38 },
  'route-120':             { x: 58, y: 30 },
  'route-121':             { x: 60, y: 32 },
  'route-122':             { x: 62, y: 42 },
  'route-123':             { x: 52, y: 45 },
  'route-124':             { x: 75, y: 42 },
  'route-125':             { x: 88, y: 45 },
  'route-126':             { x: 75, y: 48 },
  'route-127':             { x: 90, y: 60 },
  'route-128':             { x: 85, y: 65 },
  'route-129':             { x: 78, y: 67 },
  'route-130':             { x: 70, y: 68 },
  'route-131':             { x: 55, y: 68 },
  'route-132':             { x: 48, y: 68 },
  'route-133':             { x: 42, y: 70 },
  'route-134':             { x: 35, y: 70 },
  'petalburg-woods':       { x: 7,  y: 50 },
  'mt-chimney':            { x: 30, y: 28 },
  'jagged-pass':           { x: 30, y: 33 },
  'fiery-path':            { x: 33, y: 33 },
  'meteor-falls':          { x: 10, y: 18 },
  'granite-cave':          { x: 16, y: 96 },
  'desert-ruins':          { x: 36, y: 28 },
  'safari-zone-hoenn':     { x: 58, y: 22 },
  'new-mauville':          { x: 33, y: 50 },
  'weather-institute':     { x: 43, y: 38 },
  'mt-pyre':               { x: 62, y: 42 },
  'sky-pillar':            { x: 60, y: 72 },
  'victory-road-hoenn':    { x: 90, y: 70 },
  'cave-of-origin':        { x: 76, y: 54 },
  'seafloor-cavern':       { x: 84, y: 60 },

  // ── SINNOH ────────────────────────────────────────────────────────────────
  'twinleaf-town':         { x: 26, y: 82 },
  'sandgem-town':          { x: 32, y: 78 },
  'jubilife-city':         { x: 26, y: 68 },
  'oreburgh-city':         { x: 38, y: 73 },
  'floaroma-town':         { x: 26, y: 55 },
  'eterna-city':           { x: 33, y: 38 },
  'hearthome-city':        { x: 55, y: 60 },
  'solaceon-town':         { x: 55, y: 48 },
  'veilstone-city':        { x: 65, y: 45 },
  'pastoria-city':         { x: 55, y: 73 },
  'celestic-town':         { x: 43, y: 45 },
  'canalave-city':         { x: 18, y: 68 },
  'snowpoint-city':        { x: 47, y: 14 },
  'sunyshore-city':        { x: 80, y: 70 },
  'pokemon-league-sinnoh': { x: 20, y: 22 },
  'resort-area':           { x: 72, y: 80 },
  'route-201':             { x: 28, y: 82 },
  'route-202':             { x: 32, y: 73 },
  'route-203':             { x: 40, y: 70 },
  'route-204':             { x: 26, y: 60 },
  'route-205':             { x: 26, y: 47 },
  'route-206':             { x: 38, y: 55 },
  'route-207':             { x: 38, y: 65 },
  'route-208':             { x: 47, y: 58 },
  'route-209':             { x: 55, y: 65 },
  'route-210':             { x: 50, y: 48 },
  'route-211':             { x: 42, y: 40 },
  'route-212':             { x: 55, y: 67 },
  'route-213':             { x: 62, y: 73 },
  'route-214':             { x: 65, y: 60 },
  'route-215':             { x: 62, y: 48 },
  'route-216':             { x: 47, y: 28 },
  'route-217':             { x: 47, y: 22 },
  'route-218':             { x: 18, y: 70 },
  'route-219':             { x: 32, y: 83 },
  'route-220':             { x: 42, y: 85 },
  'route-221':             { x: 50, y: 82 },
  'route-222':             { x: 73, y: 72 },
  'route-223':             { x: 78, y: 60 },
  'route-224':             { x: 80, y: 50 },
  'route-225':             { x: 72, y: 42 },
  'route-226':             { x: 72, y: 55 },
  'route-227':             { x: 68, y: 32 },
  'route-228':             { x: 68, y: 40 },
  'route-229':             { x: 72, y: 80 },
  'route-230':             { x: 76, y: 80 },
  'oreburgh-mine':         { x: 38, y: 76 },
  'mt-coronet':            { x: 43, y: 40 },
  'eterna-forest':         { x: 27, y: 43 },
  'valley-windworks':      { x: 26, y: 58 },
  'great-marsh':           { x: 55, y: 72 },
  'solaceon-ruins':        { x: 55, y: 46 },
  'iron-island':           { x: 10, y: 55 },
  'lake-verity':           { x: 24, y: 73 },
  'lake-valor':            { x: 58, y: 75 },
  'lake-acuity':           { x: 40, y: 18 },
  'victory-road-sinnoh':   { x: 18, y: 28 },
  'wayward-cave':          { x: 38, y: 55 },
  'stark-mountain':        { x: 68, y: 30 },
  'fuego-ironworks':       { x: 20, y: 52 },

  // ── UNOVA ─────────────────────────────────────────────────────────────────
  'nuvema-town':           { x: 65, y: 83 },
  'accumula-town':         { x: 53, y: 78 },
  'striaton-city':         { x: 35, y: 70 },
  'nacrene-city':          { x: 28, y: 58 },
  'castelia-city':         { x: 43, y: 72 },
  'nimbasa-city':          { x: 55, y: 63 },
  'driftveil-city':        { x: 43, y: 57 },
  'mistralton-city':       { x: 35, y: 47 },
  'icirrus-city':          { x: 28, y: 35 },
  'opelucid-city':         { x: 58, y: 32 },
  'lacunosa-town':         { x: 67, y: 40 },
  'undella-town':          { x: 75, y: 48 },
  'pinwheel-forest':       { x: 27, y: 52 },
  'lostlorn-forest':       { x: 56, y: 63 },
  'cold-storage':          { x: 42, y: 57 },
  'chargestone-cave':      { x: 40, y: 52 },
  'twist-mountain':        { x: 32, y: 38 },
  'dragonspiral-tower':    { x: 28, y: 30 },
  'giant-chasm':           { x: 64, y: 40 },
  'victory-road-unova':    { x: 60, y: 22 },
  'reversal-mountain':     { x: 68, y: 53 },
  'seaside-cave':          { x: 73, y: 56 },
  'abundant-shrine':       { x: 58, y: 55 },
  'pokemon-village':       { x: 60, y: 28 },

  // ── KALOS ─────────────────────────────────────────────────────────────────
  'vaniville-town':        { x: 27, y: 87 },
  'aquacorde-town':        { x: 35, y: 84 },
  'santalune-city':        { x: 43, y: 77 },
  'lumiose-city':          { x: 55, y: 63 },
  'camphrier-town':        { x: 38, y: 65 },
  'cyllage-city':          { x: 62, y: 60 },
  'ambrette-town':         { x: 68, y: 58 },
  'geosenge-town':         { x: 55, y: 50 },
  'shalour-city':          { x: 44, y: 52 },
  'coumarine-city':        { x: 33, y: 50 },
  'laverre-city':          { x: 24, y: 43 },
  'dendemille-town':       { x: 55, y: 40 },
  'anistar-city':          { x: 70, y: 43 },
  'couriway-town':         { x: 65, y: 33 },
  'snowbelle-city':        { x: 28, y: 30 },
  'kiloude-city':          { x: 72, y: 72 },
  'kalos-route-1':         { x: 30, y: 86 },
  'kalos-route-2':         { x: 36, y: 80 },
  'kalos-route-3':         { x: 43, y: 82 },
  'kalos-route-4':         { x: 50, y: 77 },
  'kalos-route-5':         { x: 43, y: 72 },
  'kalos-route-6':         { x: 43, y: 65 },
  'kalos-route-7':         { x: 40, y: 62 },
  'kalos-route-8':         { x: 58, y: 65 },
  'kalos-route-9':         { x: 65, y: 60 },
  'kalos-route-10':        { x: 61, y: 54 },
  'kalos-route-11':        { x: 65, y: 50 },
  'kalos-route-12':        { x: 72, y: 52 },
  'kalos-route-13':        { x: 75, y: 58 },
  'kalos-route-14':        { x: 72, y: 63 },
  'kalos-route-15':        { x: 65, y: 68 },
  'kalos-route-16':        { x: 40, y: 55 },
  'kalos-route-17':        { x: 33, y: 55 },
  'kalos-route-18':        { x: 25, y: 58 },
  'kalos-route-19':        { x: 35, y: 43 },
  'kalos-route-20':        { x: 35, y: 37 },
  'kalos-route-21':        { x: 35, y: 30 },
  'kalos-route-22':        { x: 27, y: 26 },
  'santalune-forest':      { x: 43, y: 80 },
  'glittering-cave':       { x: 68, y: 55 },
  'connecting-cave':       { x: 55, y: 52 },
  'frost-cavern':          { x: 60, y: 42 },
  'reflection-cave':       { x: 58, y: 54 },
  'victory-road-kalos':    { x: 27, y: 23 },

  // ── ALOLA ─────────────────────────────────────────────────────────────────
  'iki-town':              { x: 25, y: 62 },
  'hau-oli-city':          { x: 18, y: 55 },
  'heahea-city':           { x: 55, y: 35 },
  'paniola-town':          { x: 47, y: 52 },
  'konikoni-city':         { x: 68, y: 50 },
  'malie-city':            { x: 55, y: 22 },
  'tapu-village':          { x: 30, y: 30 },
  'seafolk-village':       { x: 55, y: 75 },
  'po-town':               { x: 40, y: 22 },
  'alola-route-1':         { x: 24, y: 60 },
  'alola-route-2':         { x: 20, y: 48 },
  'alola-route-3':         { x: 28, y: 42 },
  'alola-route-4':         { x: 42, y: 48 },
  'alola-route-5':         { x: 50, y: 50 },
  'alola-route-6':         { x: 60, y: 43 },
  'alola-route-7':         { x: 62, y: 50 },
  'alola-route-8':         { x: 50, y: 28 },
  'alola-route-9':         { x: 48, y: 22 },
  'alola-route-10':        { x: 58, y: 22 },
  'alola-route-11':        { x: 38, y: 28 },
  'alola-route-12':        { x: 35, y: 32 },
  'alola-route-13':        { x: 28, y: 23 },
  'alola-route-14':        { x: 22, y: 27 },
  'alola-route-15':        { x: 43, y: 58 },
  'alola-route-16':        { x: 48, y: 65 },
  'alola-route-17':        { x: 55, y: 65 },
  'ten-carat-hill':        { x: 14, y: 52 },
  'verdant-cavern':        { x: 26, y: 42 },
  'melemele-sea':          { x: 15, y: 70 },
  'kala-e-bay':            { x: 14, y: 40 },
  'big-wave-beach':        { x: 18, y: 65 },
  'seaward-cave':          { x: 18, y: 48 },

  // ── GALAR ─────────────────────────────────────────────────────────────────
  'postwick':              { x: 50, y: 90 },
  'wedgehurst':            { x: 50, y: 83 },
  'motostoke':             { x: 36, y: 73 },
  'turffield':             { x: 32, y: 52 },
  'hulbury':               { x: 55, y: 60 },
  'hammerlocke':           { x: 50, y: 43 },
  'stow-on-side':          { x: 27, y: 33 },
  'ballonlea':             { x: 38, y: 25 },
  'circhester':            { x: 55, y: 25 },
  'spikemuth':             { x: 36, y: 15 },
  'wyndon':                { x: 50, y: 14 },
  'wild-area':             { x: 46, y: 65 },
  'galar-mine':            { x: 38, y: 72 },
  'galar-mine-no-2':       { x: 42, y: 60 },
  'glimwood-tangle':       { x: 35, y: 28 },
  'crown-tundra':          { x: 25, y: 20 },
  'isle-of-armor':         { x: 75, y: 28 },
  'galar-route-1':         { x: 50, y: 88 },
  'galar-route-2':         { x: 55, y: 75 },
  'galar-route-3':         { x: 38, y: 68 },
  'galar-route-4':         { x: 45, y: 58 },
  'galar-route-5':         { x: 55, y: 52 },
  'galar-route-6':         { x: 50, y: 48 },
  'galar-route-7':         { x: 38, y: 38 },
  'galar-route-8':         { x: 55, y: 32 },
  'galar-route-9':         { x: 60, y: 40 },
  'galar-route-10':        { x: 50, y: 28 },

  // ── HISUI ─────────────────────────────────────────────────────────────────
  'jubilife-village':      { x: 38, y: 65 },
  'obsidian-fieldlands':   { x: 38, y: 55 },
  'crimson-mirelands':     { x: 60, y: 55 },
  'cobalt-coastlands':     { x: 50, y: 73 },
  'coronet-highlands':     { x: 45, y: 38 },
  'alabaster-icelands':    { x: 42, y: 23 },

  // ── PALDEA ────────────────────────────────────────────────────────────────
  'cabo-poco':             { x: 44, y: 82 },
  'mesagoza':              { x: 50, y: 55 },
  'cortondo':              { x: 30, y: 65 },
  'artazon':               { x: 67, y: 62 },
  'levincia':              { x: 78, y: 48 },
  'cascarrafa':            { x: 25, y: 50 },
  'medali':                { x: 35, y: 40 },
  'montenevera':           { x: 52, y: 25 },
  'alfornada':             { x: 28, y: 72 },
  'glaseado-mountain':     { x: 52, y: 22 },
  'area-zero':             { x: 50, y: 45 },
  'south-paldean-sea':     { x: 50, y: 90 },
};
